# Generated by Django 4.1.3 on 2022-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=256)),
                ('contactNo', models.CharField(max_length=10)),
                ('contactImg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
